version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    container_name: rabbitmq

#  driveAndDelivery:
#    build:
#      dockerfile: Dockerfile
#    container_name: driveAndDelivery
#    image: drive-and-delivery
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#      - rabbitmq

# Names our volume
volumes:
  mysql-data:
    driver: local
  rabbitmq-data:
    driver: local